version: '3.8'
services:
  api:
    build: .
    container_name: "contrate-cientista-language-api"
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=<Key>
      - AWS_ACCESS_KEY=<Key>
      - AWS_SECRET_KEY=<Key>
      - AZURE_LANGUAGE_KEY=<Key>